# Generated by Django 5.0.7 on 2024-08-04 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_ticket_alter_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ticket',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='reviews.ticket'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(),
        ),
    ]
